# Generated by Django 6.1.1 on 2026-09-19 06:38

import cuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('placement', models.CharField(choices=[('HEADER', 'Header'), ('IN_ARTICLE', 'In Article'), ('SIDEBAR', 'Sidebar'), ('HOMEPAGE', 'Homepage'), ('VIDEO_PAGE', 'Video Page'), ('PODCAST_PAGE', 'Podcast Page'), ('FOOTER', 'Footer')], max_length=50)),
                ('creativeUrl', models.CharField(blank=True, max_length=1024, null=True)),
                ('targetUrl', models.CharField(blank=True, max_length=1024, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Advertisement',
                'indexes': [models.Index(fields=['placement', 'isActive'], name='Advertiseme_placeme_365596_idx')],
            },
        ),
    ]
