# Generated by Django 6.1.1 on 2026-09-19 06:38

import cuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=1024)),
                ('bio', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Guest',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(default='The Top Interview Podcasts', max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Podcast',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('category', models.CharField(max_length=255)),
                ('thumbnail', models.CharField(max_length=1024)),
                ('youtubeId', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished')], default='DRAFT', max_length=50)),
                ('views', models.IntegerField(default=0)),
                ('publishedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Video',
                'indexes': [models.Index(fields=['status', 'publishedAt'], name='Video_status_6b0dc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('topic', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('body', models.TextField()),
                ('thumbnail', models.CharField(max_length=1024)),
                ('videoUrl', models.CharField(blank=True, max_length=1024, null=True)),
                ('duration', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished')], default='DRAFT', max_length=50)),
                ('views', models.IntegerField(default=0)),
                ('publishedAt', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(db_column='guestId', on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='media_content.guest')),
                ('reporter', models.ForeignKey(db_column='reporterId', on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='news.reporter')),
            ],
            options={
                'db_table': 'Interview',
                'indexes': [models.Index(fields=['status', 'publishedAt'], name='Interview_status_8ff5e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('episodeNumber', models.IntegerField()),
                ('title', models.CharField(max_length=512)),
                ('guestName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover', models.CharField(max_length=1024)),
                ('audioUrl', models.CharField(max_length=1024)),
                ('duration', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=255)),
                ('youtubeUrl', models.CharField(blank=True, max_length=1024, null=True)),
                ('spotifyUrl', models.CharField(blank=True, max_length=1024, null=True)),
                ('applePodcastsUrl', models.CharField(blank=True, max_length=1024, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished')], default='DRAFT', max_length=50)),
                ('plays', models.IntegerField(default=0)),
                ('publishedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('podcast', models.ForeignKey(db_column='podcastId', on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='media_content.podcast')),
            ],
            options={
                'db_table': 'PodcastEpisode',
                'indexes': [models.Index(fields=['status', 'publishedAt'], name='PodcastEpis_status_82ecdb_idx')],
                'unique_together': {('podcast', 'episodeNumber')},
            },
        ),
    ]
