# Generated by Django 6.1.1 on 2026-09-19 06:38

import cuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribedAt', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'NewsletterSubscriber',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('SPAM', 'Spam')], default='PENDING', max_length=50)),
                ('submittedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ContactSubmission',
                'indexes': [models.Index(fields=['status', 'submittedAt'], name='ContactSubm_status_220448_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsSubmission',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('PUBLIC_VOICE', 'Public Voice'), ('NEWS_TIP', 'News Tip')], default='PUBLIC_VOICE', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mediaUrl', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('submittedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'NewsSubmission',
                'indexes': [models.Index(fields=['status', 'submittedAt'], name='NewsSubmiss_status_1d6a95_idx')],
            },
        ),
    ]
