// Frozen seed content — not typed against live @/lib/types, which can evolve independently.
import { thumb } from "@/lib/images";

export const newsArticles = [
  {
    slug: "lucknow-drainage-crisis-ground-zero",
    type: "ground-report",
    headline: "Ground Zero: What Is Really Happening in Lucknow's Flooded Colonies?",
    subheadline: "Three weeks after the first complaint, residents of Indira Nagar say the water hasn't receded — and neither has the administration's silence.",
    category: "Ground Reports",
    location: "Indira Nagar",
    state: "Uttar Pradesh",
    image: thumb("lucknow-drainage"),
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    excerpt:
      "The Top Interview travelled to Indira Nagar in Lucknow to meet families who have been wading through knee-deep water for three weeks, after a monsoon drain collapse went unrepaired.",
    body: [
      "It takes less than five minutes of walking through Indira Nagar's Sector 14 to understand why residents are furious. Stagnant water, greenish and still, sits at the mouth of nearly every lane. Children step over it on bricks laid by neighbours; shopkeepers have raised their shutters a foot off the ground with scrap wood.",
      "\"We have complained six times since the first week of the rains,\" said Meena Devi, a resident of Sector 14 for eighteen years. \"Nobody has come. We are told the file has moved to another department.\"",
      "The Top Interview visited the site with a hand-held camera and spoke to twelve households over two days. The pattern was consistent: a drain constructed in 2019 collapsed under heavy rain, but responsibility for repair has moved between the municipal corporation and the state PWD without resolution.",
      "Local corporator Ashok Tiwari, when reached by phone, said a repair tender had been \"approved in principle\" but could not confirm a timeline. Municipal engineer S.K. Verma disputed this, saying no file had reached his desk as of the date of our visit.",
      "For families like Meena Devi's, the dispute over paperwork is beside the point. \"Our house floods every time it rains now. Tell us who is responsible, and we will go to them ourselves,\" she said.",
    ],
    quote: {
      text: "Our house floods every time it rains now. Tell us who is responsible, and we will go to them ourselves.",
      attribution: "Meena Devi, resident, Sector 14",
    },
    keyPoints: [
      "A collapsed monsoon drain in Indira Nagar's Sector 14 has left homes flooded for three weeks.",
      "Twelve households interviewed on the ground describe repeated, unanswered complaints.",
      "Municipal corporation and state PWD each say responsibility lies with the other department.",
      "No confirmed repair timeline has been given to residents as of publication.",
    ],
    reporter: "rahul-kumar",
    publishedAt: "2026-09-03T09:15:00+05:30",
    updatedAt: "2026-09-04T11:00:00+05:30",
    tags: ["Lucknow", "Infrastructure", "Ground Report", "Uttar Pradesh", "Public Issues"],
    isBreaking: false,
    isFeatured: true,
    factCheck: "Verified",
    contentLabel: "News",
    views: 84210,
    readMinutes: 6,
  },
  {
    slug: "patna-flyover-collapse-breaking",
    type: "news",
    headline: "Breaking: Under-Construction Flyover Section Collapses Near Patna Junction",
    subheadline: "No casualties reported so far; traffic diverted as officials inspect structural cause.",
    category: "Breaking News",
    location: "Patna Junction",
    state: "Bihar",
    image: thumb("patna-flyover"),
    excerpt:
      "A partially built flyover span near Patna Junction collapsed late Thursday night. Authorities have cordoned off the area and traffic has been diverted to adjoining roads.",
    body: [
      "A section of an under-construction flyover near Patna Junction collapsed shortly after 11 PM on Thursday, according to eyewitnesses and local police. No injuries have been reported as the site was largely empty at the time.",
      "The Top Interview's Mohammed Imran reached the spot within the hour and spoke to night-shift labourers who had left the site less than thirty minutes before the collapse.",
      "\"We heard a loud crack and then the whole span came down,\" said one worker, who did not wish to be named. Police have cordoned off a 200-metre radius and traffic has been diverted via Ashok Rajpath.",
      "This is a developing story and will be updated as officials release more information.",
    ],
    reporter: "mohammed-imran",
    publishedAt: "2026-09-05T06:40:00+05:30",
    tags: ["Patna", "Breaking News", "Infrastructure", "Bihar"],
    isBreaking: true,
    isFeatured: false,
    factCheck: "Under Review",
    contentLabel: "News",
    views: 152340,
    readMinutes: 3,
  },
  {
    slug: "up-teacher-vacancies-education-crisis",
    type: "news",
    headline: "1.6 Lakh Teaching Posts Vacant in UP Government Schools, Data Shows",
    subheadline: "RTI response reveals scale of the shortfall as new academic year begins with overcrowded classrooms.",
    category: "Education",
    location: "Lucknow",
    state: "Uttar Pradesh",
    image: thumb("up-schools"),
    excerpt:
      "An RTI filed by The Top Interview shows over 1.6 lakh sanctioned teaching posts remain vacant across UP's government primary and secondary schools.",
    body: [
      "Government data obtained through a Right to Information request shows that 1,61,432 sanctioned teaching posts remain vacant across Uttar Pradesh's government schools as of this academic year.",
      "The shortfall is most acute in Bundelkhand and eastern UP districts, where several schools are being run by a single teacher managing multiple grades simultaneously.",
      "\"I teach classes one through five together in one room,\" said a primary school teacher in Chitrakoot district, who has been in the post for eleven years. \"There is no way to give each child proper attention.\"",
      "The state education department did not respond to requests for comment by the time of publication. This article will be updated if a response is received.",
    ],
    reporter: "ananya-singh",
    publishedAt: "2026-09-02T08:00:00+05:30",
    tags: ["Education", "Uttar Pradesh", "Public Issues", "RTI"],
    isFeatured: true,
    factCheck: "Verified",
    contentLabel: "News",
    views: 61200,
    readMinutes: 5,
  },
  {
    slug: "mp-assembly-monsoon-session-politics",
    type: "news",
    headline: "MP Assembly's Monsoon Session Ends in Uproar Over Farmer Compensation",
    subheadline: "Opposition stages walkout demanding immediate release of crop damage funds.",
    category: "Politics",
    location: "Bhopal",
    state: "Madhya Pradesh",
    image: thumb("mp-assembly"),
    excerpt:
      "The monsoon session of the Madhya Pradesh assembly concluded Wednesday with opposition MLAs staging a walkout over delayed farmer compensation payouts.",
    body: [
      "The Madhya Pradesh Legislative Assembly's monsoon session ended in disarray on Wednesday as opposition members walked out of the house, alleging the government had failed to release promised compensation for crop damage from July's excess rainfall.",
      "The state agriculture minister told the house that survey work in affected districts was \"90 percent complete\" and disbursement would begin within a month, a timeline the opposition called \"vague and repeated from the last session.\"",
      "The Top Interview's Priya Sharma tracked the session from the press gallery and spoke to MLAs from both sides after proceedings ended.",
    ],
    reporter: "priya-sharma",
    publishedAt: "2026-09-01T18:30:00+05:30",
    tags: ["Madhya Pradesh", "Politics", "Farmers", "Assembly"],
    factCheck: "Verified",
    contentLabel: "News",
    views: 38900,
    readMinutes: 4,
  },
  {
    slug: "jaipur-water-tanker-mafia-investigation",
    type: "ground-report",
    headline: "Ground Report: Inside Jaipur's Illegal Water Tanker Network",
    subheadline: "As borewells run dry, residents pay unregulated rates to private tankers operating without licenses.",
    category: "Ground Reports",
    location: "Vaishali Nagar",
    state: "Rajasthan",
    image: thumb("jaipur-water"),
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    excerpt:
      "In Jaipur's Vaishali Nagar, residents describe paying up to five times the municipal rate to unlicensed water tankers as groundwater levels fall.",
    body: [
      "Vaishali Nagar's borewells have gone dry for the third summer running. What has replaced them is a network of private water tankers — some licensed, many not — supplying households at rates residents say are impossible to verify or complain about.",
      "The Top Interview's Vikram Rathore spent three days filming tanker movements and speaking to drivers, residents, and municipal officials.",
      "\"There is no meter, no receipt. You pay what they ask or your tank stays empty,\" said Rajendra Bhatt, a resident of D-Block.",
      "Municipal officials acknowledged the existence of unlicensed operators but said enforcement was hampered by a shortage of inspection staff.",
    ],
    reporter: "vikram-rathore",
    publishedAt: "2026-08-30T10:00:00+05:30",
    tags: ["Jaipur", "Water Crisis", "Ground Report", "Rajasthan"],
    isFeatured: true,
    factCheck: "Verified",
    contentLabel: "News",
    views: 47600,
    readMinutes: 7,
  },
  {
    slug: "mumbai-startup-funding-business-report",
    type: "news",
    headline: "Mumbai Fintech Startup Raises ₹120 Crore in Series B Round",
    subheadline: "Funding to be used for expansion into tier-2 cities and new lending products.",
    category: "Business",
    location: "Mumbai",
    state: "Maharashtra",
    image: thumb("mumbai-fintech"),
    excerpt:
      "A Mumbai-based fintech startup focused on small-business lending has closed a ₹120 crore Series B round led by two international investors.",
    body: [
      "The company, which offers short-term working capital loans to small retailers, said the funding would go toward expanding operations into 40 additional tier-2 cities over the next 18 months.",
      "\"We've proven the model in metro markets. The real opportunity is in cities where formal credit access is still limited,\" the company's co-founder told The Top Interview.",
    ],
    reporter: "sneha-deshmukh",
    publishedAt: "2026-08-29T14:00:00+05:30",
    tags: ["Business", "Startups", "Mumbai", "Fintech"],
    contentLabel: "News",
    views: 22100,
    readMinutes: 3,
  },
  {
    slug: "delhi-air-quality-winter-preview",
    type: "news",
    headline: "Delhi's Air Quality Panel Meets Early This Year Amid Fears of Worse Winter",
    subheadline: "Officials cite stubble burning satellite data and construction dust as key concerns ahead of the season.",
    category: "National News",
    location: "New Delhi",
    state: "Delhi",
    image: thumb("delhi-air"),
    excerpt:
      "Delhi's air quality management commission convened an early planning session this year, citing satellite data pointing to an early start to stubble burning in neighbouring states.",
    body: [
      "Officials from the Commission for Air Quality Management met representatives from Punjab, Haryana and Uttar Pradesh on Tuesday to coordinate an early response plan, months ahead of the usual winter smog season.",
      "\"We are seeing fire counts roughly 12 percent higher than the same period last year,\" a commission official said, citing satellite monitoring data.",
    ],
    reporter: "ananya-singh",
    publishedAt: "2026-08-28T09:45:00+05:30",
    tags: ["Delhi", "Environment", "Air Quality"],
    contentLabel: "News",
    views: 31500,
    readMinutes: 4,
  },
  {
    slug: "kanpur-crime-safety-women-helpline",
    type: "news",
    headline: "Kanpur's Women Safety Helpline Sees 40% Rise in Calls, Officials Say Awareness Driving Numbers",
    subheadline: "Police say increased reporting reflects growing trust in the helpline, not a rise in incidents alone.",
    category: "Crime & Safety",
    location: "Kanpur",
    state: "Uttar Pradesh",
    image: thumb("kanpur-helpline"),
    excerpt:
      "Kanpur police say the 1090 women's safety helpline has recorded a 40 percent year-on-year rise in calls, which they attribute largely to awareness campaigns in colleges and markets.",
    body: [
      "Senior Superintendent of Police, Kanpur, told The Top Interview that the increase reflects growing willingness among women to report incidents rather than a sharp rise in crime itself, though the department is reviewing patrol patterns in three identified hotspot areas.",
    ],
    reporter: "rahul-kumar",
    publishedAt: "2026-08-27T12:00:00+05:30",
    tags: ["Kanpur", "Crime & Safety", "Women Safety"],
    contentLabel: "News",
    views: 18700,
    readMinutes: 3,
  },
  {
    slug: "bollywood-ott-release-entertainment",
    type: "news",
    headline: "Anticipated Drama Series Skips Theatres for Direct OTT Release",
    subheadline: "Producers cite shifting viewership patterns as streaming platforms outbid theatrical distributors.",
    category: "Entertainment",
    location: "Mumbai",
    state: "Maharashtra",
    image: thumb("ott-release"),
    excerpt:
      "One of the year's most anticipated drama series will skip a theatrical run entirely, releasing directly on a streaming platform next month.",
    body: [
      "The decision reflects a broader industry shift, with producers increasingly favouring guaranteed streaming deals over theatrical box-office risk, especially for dialogue-driven dramas.",
    ],
    reporter: "sneha-deshmukh",
    publishedAt: "2026-08-26T16:20:00+05:30",
    tags: ["Entertainment", "OTT", "Bollywood"],
    contentLabel: "News",
    views: 44300,
    readMinutes: 2,
  },
  {
    slug: "rajasthan-cricket-academy-sports",
    type: "news",
    headline: "Rajasthan's New State-Funded Cricket Academy Opens Doors to Rural Talent",
    subheadline: "Academy offers free coaching and hostel facilities to selected under-16 players from district trials.",
    category: "Sports",
    location: "Jaipur",
    state: "Rajasthan",
    image: thumb("cricket-academy"),
    excerpt:
      "Rajasthan's sports department has opened a new residential cricket academy aimed at identifying talent from rural districts often overlooked by private academies.",
    body: [
      "The first batch of 40 players was selected through open trials held across 12 districts, with the state covering coaching, boarding and equipment costs for selected candidates.",
    ],
    reporter: "vikram-rathore",
    publishedAt: "2026-08-25T11:10:00+05:30",
    tags: ["Sports", "Cricket", "Rajasthan"],
    contentLabel: "News",
    views: 27800,
    readMinutes: 3,
  },
  {
    slug: "bihar-migrant-workers-social-issue",
    type: "ground-report",
    headline: "Ground Report: The Villages Bihar's Migrant Workers Send Money Home To — But Rarely Return",
    subheadline: "In Muzaffarpur's outlying villages, entire streets are supported by remittances from workers in distant cities.",
    category: "Social Issues",
    location: "Muzaffarpur",
    state: "Bihar",
    image: thumb("bihar-migrants"),
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    excerpt:
      "The Top Interview visited villages outside Muzaffarpur where entire local economies now depend on remittances from migrant workers employed in construction sites hundreds of kilometres away.",
    body: [
      "Walk through Bariyarpur village on a weekday afternoon and you'll notice something missing: men between the ages of 20 and 45. Most are in Surat, Delhi or Bengaluru, working construction and factory jobs, sending money home every month.",
      "\"My husband comes home twice a year, for ten days each time,\" said Sunita Devi, whose family has relied on remittances for six years. \"The children barely know him.\"",
      "Local panchayat records estimate over 60 percent of working-age men from the village currently live outside the state.",
    ],
    reporter: "mohammed-imran",
    publishedAt: "2026-08-24T09:00:00+05:30",
    tags: ["Bihar", "Migration", "Social Issues", "Ground Report"],
    isFeatured: true,
    factCheck: "Verified",
    contentLabel: "News",
    views: 52900,
    readMinutes: 6,
  },
  {
    slug: "up-tech-startup-hub-noida",
    type: "news",
    headline: "Noida Emerges as Second Hub for AI Startups Outside Bengaluru, Report Finds",
    subheadline: "Lower office rents and proximity to Delhi's talent pool are cited as key drivers.",
    category: "Technology",
    location: "Noida",
    state: "Uttar Pradesh",
    image: thumb("noida-tech"),
    excerpt:
      "A new industry report places Noida among the top three emerging hubs for AI and deep-tech startups in India, driven by lower costs and access to Delhi-NCR's engineering talent.",
    body: [
      "The report notes a 34 percent increase in registered AI-focused startups in Noida over the past two years, with several citing lower office rents compared to Bengaluru and Gurugram as a deciding factor.",
    ],
    reporter: "ananya-singh",
    publishedAt: "2026-08-22T10:30:00+05:30",
    tags: ["Technology", "Startups", "Noida", "AI"],
    contentLabel: "News",
    views: 29400,
    readMinutes: 4,
  },
  {
    slug: "indore-cleanest-city-public-issue",
    type: "news",
    headline: "Indore's 'Cleanest City' Tag Faces Test as Waste Segregation Slips in New Wards",
    subheadline: "Officials say expansion into newly merged municipal wards has strained existing systems.",
    category: "Public Issues",
    location: "Indore",
    state: "Madhya Pradesh",
    image: thumb("indore-waste"),
    excerpt:
      "Indore, long celebrated for its waste management model, is facing new challenges as newly added municipal wards struggle to keep pace with segregation and collection standards.",
    body: [
      "Municipal officials admit that six wards merged into the city limits last year are yet to be fully integrated into the door-to-door segregation system that made Indore a national model.",
    ],
    reporter: "priya-sharma",
    publishedAt: "2026-08-20T13:00:00+05:30",
    tags: ["Indore", "Public Issues", "Waste Management"],
    contentLabel: "News",
    views: 19800,
    readMinutes: 3,
  },
  {
    slug: "delhi-metro-phase-4-national",
    type: "news",
    headline: "Delhi Metro Phase 4 Corridor to Open Two New Sections by December",
    subheadline: "DMRC says trial runs are underway on both stretches ahead of commercial launch.",
    category: "National News",
    location: "New Delhi",
    state: "Delhi",
    image: thumb("delhi-metro"),
    excerpt:
      "The Delhi Metro Rail Corporation says two Phase 4 corridor sections are on track to open to the public by December, following successful trial runs this month.",
    body: [
      "The two stretches will add over 15 kilometres of coverage, primarily benefiting commuters in the city's southwestern and northeastern extensions.",
    ],
    reporter: "ananya-singh",
    publishedAt: "2026-08-18T08:15:00+05:30",
    tags: ["Delhi", "Metro", "Infrastructure"],
    contentLabel: "News",
    views: 33600,
    readMinutes: 3,
  },
];

