// Frozen seed content — not typed against live @/lib/types, which can evolve independently.
import { portrait } from "@/lib/images";

export const reporters = [
  {
    slug: "rahul-kumar",
    name: "Rahul Kumar",
    designation: "Ground Reporter",
    location: "Lucknow, Uttar Pradesh",
    bio: "Rahul has spent eight years reporting directly from villages and district towns across Uttar Pradesh, covering everything from farmer protests to civic infrastructure failures. He believes the real story is always found outside the studio.",
    photo: portrait("rahul-kumar"),
    twitter: "https://x.com/rahulkumar_tti",
    instagram: "https://instagram.com/rahulkumar_tti",
    email: "rahul.kumar@thetopinterview.in",
    articleCount: 214,
    groundReportCount: 96,
    interviewCount: 18,
  },
  {
    slug: "ananya-singh",
    name: "Ananya Singh",
    designation: "Senior Correspondent",
    location: "New Delhi",
    bio: "Ananya covers national politics and policy from Delhi, with a decade of experience across print and television newsrooms before joining The Top Interview to focus on long-form, verified reporting.",
    photo: portrait("ananya-singh"),
    twitter: "https://x.com/ananyasingh_tti",
    email: "ananya.singh@thetopinterview.in",
    articleCount: 341,
    groundReportCount: 44,
    interviewCount: 62,
  },
  {
    slug: "mohammed-imran",
    name: "Mohammed Imran",
    designation: "Ground Reporter",
    location: "Patna, Bihar",
    bio: "Imran reports on public infrastructure, education and flood-affected communities across Bihar. His interviews with local residents have driven several administrative follow-ups on stalled projects.",
    photo: portrait("mohammed-imran"),
    instagram: "https://instagram.com/imran_tti",
    email: "mohammed.imran@thetopinterview.in",
    articleCount: 178,
    groundReportCount: 112,
    interviewCount: 21,
  },
  {
    slug: "priya-sharma",
    name: "Priya Sharma",
    designation: "Political Editor",
    location: "Bhopal, Madhya Pradesh",
    bio: "Priya leads our political desk, tracking state assembly proceedings, candidate interviews and grassroots political sentiment across Madhya Pradesh and neighbouring states.",
    photo: portrait("priya-sharma"),
    twitter: "https://x.com/priyasharma_tti",
    email: "priya.sharma@thetopinterview.in",
    articleCount: 296,
    groundReportCount: 38,
    interviewCount: 74,
  },
  {
    slug: "vikram-rathore",
    name: "Vikram Rathore",
    designation: "Video Journalist",
    location: "Jaipur, Rajasthan",
    bio: "Vikram shoots and edits our ground report films across Rajasthan, specialising in long-form documentary style coverage of water scarcity, tourism and rural livelihoods.",
    photo: portrait("vikram-rathore"),
    instagram: "https://instagram.com/vikram_tti",
    email: "vikram.rathore@thetopinterview.in",
    articleCount: 89,
    groundReportCount: 143,
    interviewCount: 12,
  },
  {
    slug: "sneha-deshmukh",
    name: "Sneha Deshmukh",
    designation: "Reporter",
    location: "Mumbai, Maharashtra",
    bio: "Sneha covers business, civic issues and entertainment out of Mumbai, with a focus on stories that connect city policy decisions to everyday residents.",
    photo: portrait("sneha-deshmukh"),
    twitter: "https://x.com/sneha_tti",
    email: "sneha.deshmukh@thetopinterview.in",
    articleCount: 156,
    groundReportCount: 29,
    interviewCount: 33,
  },
];

export function getReporterBySlug(slug: string) {
  return reporters.find((r) => r.slug === slug);
}
