# Generated by Django 6.1.1 on 2026-09-19 06:38

import cuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('photo', models.CharField(max_length=1024)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, db_column='locationId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporters', to='core.city')),
                ('user', models.OneToOneField(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporterProfile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Reporter',
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('headline', models.CharField(max_length=512)),
                ('subheadline', models.CharField(blank=True, max_length=512, null=True)),
                ('excerpt', models.TextField()),
                ('body', models.TextField()),
                ('image', models.CharField(max_length=1024)),
                ('videoUrl', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished')], default='DRAFT', max_length=50)),
                ('contentLabel', models.CharField(choices=[('NEWS', 'News'), ('OPINION', 'Opinion'), ('SPONSORED', 'Sponsored')], default='NEWS', max_length=50)),
                ('factCheck', models.CharField(blank=True, choices=[('VERIFIED', 'Verified'), ('UNDER_REVIEW', 'Under Review'), ('DISPUTED', 'Disputed')], max_length=50, null=True)),
                ('isBreaking', models.BooleanField(default=False)),
                ('isFeatured', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('readMinutes', models.IntegerField(default=3)),
                ('quoteText', models.TextField(blank=True, null=True)),
                ('quoteAttribution', models.CharField(blank=True, max_length=255, null=True)),
                ('keyPoints', models.JSONField(blank=True, null=True)),
                ('locationLabel', models.CharField(blank=True, max_length=255, null=True)),
                ('publishedAt', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(db_column='categoryId', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.category')),
                ('city', models.ForeignKey(blank=True, db_column='cityId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.city')),
                ('tags', models.ManyToManyField(db_table='_ArticleTags', related_name='articles', to='core.tag')),
                ('reporter', models.ForeignKey(db_column='reporterId', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.reporter')),
            ],
            options={
                'db_table': 'NewsArticle',
            },
        ),
        migrations.CreateModel(
            name='GroundReport',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('headline', models.CharField(max_length=512)),
                ('excerpt', models.TextField()),
                ('body', models.TextField()),
                ('image', models.CharField(max_length=1024)),
                ('videoUrl', models.CharField(blank=True, max_length=1024, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('mapQuery', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished')], default='DRAFT', max_length=50)),
                ('views', models.IntegerField(default=0)),
                ('locationLabel', models.CharField(blank=True, max_length=255, null=True)),
                ('publishedAt', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, db_column='cityId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groundReports', to='core.city')),
                ('reporter', models.ForeignKey(db_column='reporterId', on_delete=django.db.models.deletion.CASCADE, related_name='groundReports', to='news.reporter')),
            ],
            options={
                'db_table': 'GroundReport',
            },
        ),
        migrations.CreateModel(
            name='SpecialReport',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('dek', models.TextField()),
                ('image', models.CharField(max_length=1024)),
                ('location', models.CharField(max_length=255)),
                ('chapters', models.JSONField()),
                ('timeline', models.JSONField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished')], default='DRAFT', max_length=50)),
                ('views', models.IntegerField(default=0)),
                ('publishedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SpecialReport',
                'indexes': [models.Index(fields=['status', 'publishedAt'], name='SpecialRepo_status_05ad3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('photo', models.CharField(max_length=1024)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('displayOrder', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TeamMember',
                'indexes': [models.Index(fields=['isActive', 'displayOrder'], name='TeamMember_isActiv_22ff45_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(db_column='articleId', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.newsarticle')),
            ],
            options={
                'db_table': 'Comment',
                'indexes': [models.Index(fields=['article', 'status'], name='Comment_article_8401a3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['category'], name='NewsArticle_categor_0ef7fe_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['status', 'publishedAt'], name='NewsArticle_status_fbb941_idx'),
        ),
        migrations.AddIndex(
            model_name='groundreport',
            index=models.Index(fields=['status', 'publishedAt'], name='GroundRepor_status_703179_idx'),
        ),
    ]
