# Generated by Django 6.1.1 on 2026-09-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='ArticleTag',
                    fields=[
                        ('article', models.ForeignKey(db_column='A', on_delete=models.CASCADE, to='news.newsarticle')),
                        ('tag', models.ForeignKey(db_column='B', on_delete=models.CASCADE, to='core.tag')),
                        ('pk', models.CompositePrimaryKey('article_id', 'tag_id')),
                    ],
                    options={
                        'db_table': '_ArticleTags',
                        'managed': False,
                    },
                ),
                migrations.AlterField(
                    model_name='newsarticle',
                    name='tags',
                    field=models.ManyToManyField(related_name='articles', through='news.ArticleTag', through_fields=('article', 'tag'), to='core.tag'),
                ),
            ],
        ),
    ]
