# Generated by Django 6.1.1 on 2026-09-19 06:38

import cuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'SiteSetting',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=1024)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SocialLink',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'State',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('eventType', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=1024)),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('occurredAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'AnalyticsEvent',
                'indexes': [models.Index(fields=['eventType', 'occurredAt'], name='AnalyticsEv_eventTy_fd29e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('state', models.ForeignKey(db_column='stateId', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.state')),
            ],
            options={
                'db_table': 'City',
                'unique_together': {('state', 'name')},
            },
        ),
    ]
